In [1]:
import sklearn as sk
import sklearn.covariance as cov
import pandas as pd
import numpy as np
from ggplot import *

data = pd.DataFrame.from_csv("inflation.csv",index_col=None)

In [2]:
def date_convert(date):
    year, month = date.split(sep='-')
    return float(year)+float(month)/12

In [7]:
usa = data[data['LOCATION']=='USA']
usa = usa[usa['SUBJECT'] == 'TOT']
usa = usa[usa['TIME'] > '2005']
usa = usa[usa['MEASURE']=='AGRWTH']
usa = usa[usa['FREQUENCY']=='M']
usa["TIME"] = usa['TIME'].map(date_convert)

In [10]:
usa[['TIME','Value']]

               TIME     Value
149311  2005.083333  2.969762
149312  2005.166667  3.007519
149313  2005.250000  3.148346
149314  2005.333333  3.510638
149315  2005.416667  2.802750
149316  2005.500000  2.530311
149317  2005.583333  3.167899
149318  2005.666667  3.641161
149319  2005.750000  4.686677
149320  2005.833333  4.347826
149321  2005.916667  3.455497
149322  2006.000000  3.415659
149323  2006.083333  3.985317
149324  2006.166667  3.597497
149325  2006.250000  3.362649
149326  2006.333333  3.545735
149327  2006.416667  4.166667
149328  2006.500000  4.318766
149329  2006.583333  4.145343
149330  2006.666667  3.818737
149331  2006.750000  2.062374
149332  2006.833333  1.305221
149333  2006.916667  1.973684
149334  2007.000000  2.540650
149335  2007.083333  2.075643
149336  2007.166667  2.415199
149337  2007.250000  2.778779
149338  2007.333333  2.573697
149339  2007.416667  2.690864
149340  2007.500000  2.687038
...             ...       ...
149424  2014.500000  2.072341
149425  2014.583333  1.992329
149426  2014.666667  1.699611
149427  2014.750000  1.657919
149428  2014.833333  1.664340
149429  2014.916667  1.322355
149430  2015.000000  0.756493
149431  2015.083333 -0.089348
149432  2015.166667 -0.025130
149433  2015.250000 -0.073637
149434  2015.333333 -0.199517
149435  2015.416667 -0.039933
149436  2015.500000  0.123771
149437  2015.583333  0.169570
149438  2015.666667  0.195079
149439  2015.750000 -0.036130
149440  2015.833333  0.170574
149441  2015.916667  0.501798
149442  2016.000000  0.729520
149443  2016.083333  1.373087
149444  2016.166667  1.017800
149445  2016.250000  0.852536
149446  2016.333333  1.125110
149447  2016.416667  1.019323
149448  2016.500000  0.997326
149449  2016.583333  0.827139
149450  2016.666667  1.062875
149451  2016.750000  1.463784
149452  2016.833333  1.635988
149453  2016.916667  1.692537

[143 rows x 2 columns]

In [9]:
usa[['TIME','Value']].to_csv("inflation_usa.csv")